#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm -C admin-web lint
pnpm -C admin-web format:check
pnpm -C admin-web typecheck
pnpm -C admin-web test -- --changed

pnpm -C functions lint
pnpm -C functions format:check
pnpm -C functions typecheck
pnpm -C functions test -- --changed
